[theme]
base = "light"
primaryColor = "#B10F1B"
backgroundColor = "#F7F7F7"
secondaryBackgroundColor = "#ECECEC"
textColor = "#171717"
linkColor = "#9C0D17"
borderColor = "#CFCFCF"
showWidgetBorder = true

[server]
headless = true
